services: 
   rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    container_name: nest_msg_rabbitmq
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
         
volumes:
  rabbitmq_data:
    driver: local
  
networks:
  default:
    name: nest_msg_network